runtime: php81

includes:
  - secret.yaml

env_variables:
  APP_ENV: production
  APP_DEBUG: false
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  LOG_CHANNEL: stdout
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
